git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"vgit config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"vgit config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"git config --global user.name "Sathwik"
git config --global user.email "YOUR_GITHUB_EMAIL"